config/routes.rb
Rails.application.routes.draw do
  resources :applications
  resources :jobs
  devise_for :users
  # get 'home/index'
  # root 'home#index'
  root 'jobs#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # can :read, :all

    user ||= User.new # guest user (not logged in)
        can :read, Application, :user_id => user.id
      if user.admin?
        can :manage, Job
        can :read, Application
        cannot :create, Application
        cannot :destroy, Application
      else
        can :read, Job
        can :create, Application
      end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application.rb
class Application < ApplicationRecord
	belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	has_many :applications
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  load_and_authorize_resource
  before_action :set_application, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:new, :destroy]

  rescue_from ActiveRecord::RecordNotFound do |exception|
    flash[:notice] = "Application not found!"
    redirect_to root_path
  end

  rescue_from CanCan::AccessDenied do |exception|
    flash[:notice] = exception.message
    redirect_to root_path
  end

  # GET /applications or /applications.json
  def index
    # @users = User.accessible_by(current_ability)
    @applications = Application.all
  end

  # GET /applications/1 or /applications/1.json
  def show
    # authorize! :show, @user
    if current_user.admin?
      @application.seen = true
      @application.save
    end



  end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications or /applications.json
  def create
    @application = Application.new(application_params)
    @application.user_id = current_user.id
    @application.job_id = params[:application][:job_id]

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: "Application was successfully created." }
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1 or /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: "Application was successfully updated." }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1 or /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: "Application was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # def correct_user

  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def application_params
      params.require(:application).permit(:app_id, :user_id, :job_id, :seen)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  load_and_authorize_resource
  before_action :set_job, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show, :index]
  
  rescue_from ActiveRecord::RecordNotFound do |exception|
    flash[:notice] = "Job not found!"
    redirect_to root_path
  end

  rescue_from CanCan::AccessDenied do |exception|
    flash[:notice] = "You are unauthorized to manage jobs!"
    redirect_to root_path
  end


  # GET /jobs or /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:job_id, :title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/applications/_form.html.erb
<%= form_with(model: application) do |form| %>
  <% if application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
        <% application.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%= hidden_field_tag :job_id, params[:job_id] %>

   <div class="field">
    <% form.label :job_id %>
    <%= form.number_field :job_id, value:params[:job_id], hidden:true %>
  </div>

<br/>

  <div class="actions">
    <%= form.submit 'Apply Now', class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing Application</h1>

<%= render 'form', application: @application %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<h1>Applications</h1>

<table class="table table-striped table-hover">
  <thead class="table-dark">
    <tr>
      <th>Job Title</th>
      <th>Status</th>
      <th></th>
      <!-- <th colspan="1"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <% @job = Job.find(application.job_id) %>

      <tr>

          <% if application.user_id == current_user.id or current_user.admin %>
  
            <td><%= @job.title %></td>
            <% if application.seen %>
              <td>seen</td>
            <% else %>
              <td>not seen</td>
            <% end %>
            <td><%= link_to 'Show', application, class:"btn btn-secondary" %></td>

        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', root_path, class:"btn btn-dark" %>

app/views/applications/new.html.erb
<% @job = Job.find(params[:job_id]) %>

<h1><%= @job.title %></h1>
<p><%= @job.description %></p>

<% if can? :create, @application %><%= render 'form', application: @application %><% end %>

<br/>

<%= link_to 'Back', root_path, class:"btn btn-dark" %>

app/views/applications/show.html.erb
<% @job = Job.find(@application.job_id) %>

<div class="h-100 p-5 bg-light rounded-3">
	<h1 class="display-6"><%= @job.title %></h1>
<p><%= @job.description %></p>

<% @user = User.find(@application.user_id) %>
<hr class="my-4">

<h1 class="display-6">Applicant</h1>
<p><%= @user.email %></p>
</div>
<br/>
<%= link_to 'Back', applications_path, class:"btn btn-dark" %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Jobs Board', root_path, class:"navbar-brand", style:"font-size:200%" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <% if can? :create, Application %>
            <%= link_to 'My job applications', applications_path, class:"nav-link" %>
          <% end %>
         <% if can? :manage, Job %>
          <%= link_to 'List job applications', applications_path, class:"nav-link" %>
          <%= link_to 'Add new job', new_job_path, class:"nav-link" %>
         <% end %>
         <% end %>
       </ul>
         <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <% if user_signed_in? %>

            <li class="nav-item">
              <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
                <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
            </li>
        <% end %>
      </ul>

<!--       <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> -->
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Jobs</h1>
<p>Please read the jobs' descriptions carefully and apply to the jobs that you feel you are fit for</p>

app/views/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <% form.label :id %>
    <%= form.number_field :id, type: :hidden %>
  </div>

  <div class="field mb-3">
    <% form.label :title %>
    <%= form.text_field :title, class:"form-control", placeholder:"Title" %>
  </div>

  <div class="field mb-3">
    <% form.label :description %>
    <%= form.text_area :description, class:"form-control", placeholder:"Description" %>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
  <br/>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job, class:"btn btn-secondary" %>
<%= link_to 'Back', jobs_path, class:"btn btn-dark" %>

app/views/jobs/index.html.erb
<h1>Jobs</h1>
<% if !Job.first.nil? %>
  <p>Please read the jobs' descriptions carefully and apply now!</p>
<% else %>
  <p>There are currently no jobs listed, please check again later</p>
<% end %>


    <% @jobs.each do |job| %>

      <div class="h-100 p-5 bg-light rounded-3">
        <h1 class="display-6"><%= job.title %></h1>

        <hr class="my-4">
        <h5>Description:</h5>
        <p>
          <h6><%= job.description %></h6>
          <%= job.job_id %>
        </p>

        
        <% if can? :create, Application %><%= link_to 'Apply', {:controller => "applications", :action => "new", :job_id => job.id }, class:"btn btn-secondary", style:"float:right" %><% end %>

        <% if can? :manage, job %><%= link_to 'Manage', job_path(job), class:"btn btn-secondary", style:"float:right" %><% end %>

      </div>
      <br/>
<% end %>
    

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path, class:"btn btn-dark" %>

app/views/jobs/show.html.erb
<div class="h-100 p-5 bg-light rounded-3">
	<h1 class="display-6"><%= @job.title %></h1>
	<hr class="my-4">
	<h5>Description:</h5>
	<p>
	  <h6><%= @job.description %></h6>
	</p>
</div>
<br/>
<% if can? :manage, @job %>
	<%= link_to 'Edit', edit_job_path(@job), class:"btn btn-secondary" %>
	<%= link_to 'Delete Job', @job, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
<% end %>
<br/>
<br/>
<%= link_to 'Back', jobs_path, class:"btn btn-dark" %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>Jobs Board</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/navbar' %>
    <div class="container">
      <br/>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>